
version: '3.8'

services:
  web:
    container_name: chatty-app-landingpage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
