name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: List build directory contents
        run: ls -la dist

      - name: Deploy to GitHub Pages
        env:
          GH_ACTION_SECRET: ${{ secrets.GH_ACTION_SECRET }}
        run: |
          git config user.name 'hkthiet2999'
          git config user.email 'smoothkt4951@gmail.com'
          git remote set-url origin https://${{ secrets.GH_ACTION_SECRET }}@github.com/hkthiet2999/chatty-landing-page.git
          npx gh-pages --dist dist
