name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Configure Git user locally
        run: |
          git config --global user.name 'hkthiet2999'
          git config --global user.email 'smoothkt4951@gmail.com'

      - name: List build directory contents
        run: ls -la dist

      - name: Deploy to GitHub Pages
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          npx gh-pages --repo https://${{ secrets.GH_PAT }}@github.com/hkthiet2999/chatty-landing-page.git --dist dist
